"""
Parameters.
"""

# set to True to download and save the MNIST dataset.
DOWNLOAD_MNIST = False

# Discriminator
DISCRIMINATOR_EPOCHS = 2
DISCRIMINATOR_BATCH_SIZE = 256
DISCRIMINATOR_TRAIN_TEST_SPLIT = 0.1

DISCRIMINATOR_INPUT_LAYER = 784
DISCRIMINATOR_HIDDEN_LAYER_1 = 512
DISCRIMINATOR_HIDDEN_LAYER_2 = 216
DISCRIMINATOR_HIDDEN_LAYER_3 = 64
DISCRIMINATOR_HIDDEN_LAYER_4 = 32
DISCRIMINATOR_HIDDEN_LAYER_5 = 2

DISCRIMINATOR_OPTIMIZER = 'adam'
DISCRIMINATOR_LOSS = 'kullback_leibler_divergence'
DISCRIMINATOR_ACTIVATION = 'sigmoid'

# Generator
GENERATOR_INPUT_LAYER = 16
GENERATOR_HIDDEN_LAYER_1 = 32
GENERATOR_HIDDEN_LAYER_2 = 128
GENERATOR_HIDDEN_LAYER_3 = 256
GENERATOR_HIDDEN_LAYER_4 = 512
GENERATOR_HIDDEN_LAYER_5 = 784

GENERATOR_ACTIVATION = 'sigmoid'

# Gan
GAN_LOSS = 'binary_crossentropy'
GAN_OPTIMIZER = 'adagrad'

GAN_GENERATOR_TRAINING_EPOCH = 2
GAN_GENERATOR_TRAINING_BATCH_SIZE = 128
